import Joi from "joi-browser";

export function getobject() {
  return {
    basic: [
      [
        {
          type: "input",
          typeName: "text",
          size: "grow2",
          name: "basic_0_0_ResPictureKey",
          label: "Image Link",
          value: undefined,
          schema: Joi.string(),
        },
        {
          type: "checkbox",
          size: "grow1",
          name: "basic_0_1_IsVeteran",
          label: "Is Veteeran?",
          value: false,
          schema: Joi.boolean(),
        },
        {
          type: "checkbox",
          size: "grow1",
          name: "basic_0_2_IsChurchAttender",
          label: "Church Attender?",
          value: false,
          schema: Joi.boolean(),
        },
        {
          type: "checkbox",
          size: "grow1",
          name: "basic_0_3_HasChildren",
          label: "Has Children?",
          value: false,
          schema: Joi.boolean(),
        },
      ],
      [
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_1_0_ResFirstName",
          label: "Resident First Name",
          value: undefined,
          schema: Joi.string().required().max(30),
        },
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_1_1_ResMiddleName",
          label: "Resident Middle Name",
          value: undefined,
          schema: Joi.string().required().max(30),
        },
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_1_2_ResLastName",
          label: "Resident Last Name",
          value: undefined,
          schema: Joi.string().required().max(30),
        },
      ],
      [
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_2_0_SSN",
          label: "SSN",
          value: undefined,
          schema: Joi.string().required().max(12),
        },
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_2_1_PSNumber",
          label: "PSNumber",
          value: undefined,
          schema: Joi.string().required().max(12),
        },
      ],
      [
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_3_0_ResEmailAddr",
          label: "Email Address",
          value: undefined,
          schema: Joi.string().email().required().max(60),
        },
        {
          type: "date",
          size: "grow1",
          name: "basic_3_1_ResBirthDate",
          label: "Date of birth",
          value: null,
          schema: Joi.date().required(),
        },
      ],
      [
        {
          type: "input",
          size: "grow1",
          typeName: "number",
          name: "basic_4_0_ResPhoneNumber",
          label: "Phone number",
          value: undefined,
          schema: Joi.number(),
        },
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_4_1_WhereRaised",
          label: "Where Raised",
          value: undefined,
          schema: Joi.string().required().max(100),
        },
      ],
      [
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_5_0_ResZipCode",
          label: "Resident Zip Code",
          value: undefined,
          schema: Joi.string().max(10),
        },
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "basic_5_1_ResAddress1",
          label: "Resident Address",
          value: undefined,
          schema: Joi.string().max(50),
        },
      ],
      [
        {
          type: "select",
          size: "grow1",
          name: "basic_6_0_ResCountry",
          label: "Resident Country",
          options: [],
          value: "United States",
          schema: Joi.string().max(30),
        },
        {
          type: "select",
          size: "grow1",
          name: "basic_6_1_ResState",
          label: "Resident State",
          options: [],
          value: undefined,
          schema: Joi.string().max(30),
        },
        {
          type: "select",
          size: "grow1",
          name: "basic_6_2_ResCity",
          label: "Resident City",
          options: [],
          value: undefined,
          schema: Joi.string().max(30),
        },
      ],
    ],
    church: [
      [
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "church_0_0_ChurchName",
          label: "Church Name",
          value: undefined,
          schema: Joi.string().max(30),
        },
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "church_0_1_ChurchLocation",
          label: "Church Location",
          value: undefined,
          schema: Joi.string().max(30),
        },
      ],
      [
        {
          type: "input",
          size: "grow1",
          typeName: "text",
          name: "church_1_0_ChurchPhone",
          label: "Church Phone",
          value: undefined,
          schema: Joi.string().max(15),
        },
        {
          type: "select",
          size: "grow1",
          name: "church_1_1_RaceListID",
          label: "Race",
          options: [],
          value: undefined,
          schema: Joi.string(),
        },
      ],
    ],
  };
}
